#ใช้ NODE.JS version 22 เป็นฐาน
FROM node:22

#สร้างโฟลเดอร์แอปพลิเคชัน
WORKDIR /usr/src/app

#Copy ไฟล์ package.json และ package-lock.json ไปยังโฟลเดอร์แอปพลิเคชัน
COPY package*.json ./
#ติดตั้ง dependencies
RUN npm install

#Copy โค้ดแอปพลิเคชันทั้งหมดไปยังโฟลเดอร์แอปพลิเคชัน
COPY . .

#เปิดพอร์ต 3000
EXPOSE 3000

#รันคำสั่งเพื่อเริ่มแอปพลิเคชัน
CMD ["node", "./src/app.js"]